rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./providers/rule/direct.yaml"
  Pilih:
    type: file
    behavior: classical
    path: "./providers/rule/pilih.yaml"
  UDP:
    type: file
    behavior: classical
    path: "./providers/rule/UDP.yaml"
proxy-providers:
  ID:
    type: file
    path: "./providers/proxy/akun-id.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  SG:
    type: file
    path: "./providers/proxy/akun-sg.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  WORLD:
    type: file
    path: "./providers/proxy/akun-world.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
proxy-groups:
  - name: PILIH
    type: select
    disable-udp: false
    use:
      - ID
      - SG
      - WORLD
  - name: UDP-Traffic
    type: select
    disable-udp: false
    proxies:
      - Failover
    use:
      - ID
      - SG
  - name: TCP-Traffic
    type: select
    disable-udp: false
    proxies:
      - Ping-Alive
      - LoadBalancing
      - Failover
      - PILIH
  - name: Indo-Traffic
    type: url-test
    disable-udp: false
    use:
      - ID
    proxies:
      - Failover
    url: http://www.gstatic.com/generate_204
    interval: '120'
    tolerance: '10'
  - name: Failover
    type: fallback
    disable-udp: false
    use:
      - ID
      - SG
      - WORLD
    url: http://www.gstatic.com/generate_204
    interval: '120'
    tolerance: '10'
  - name: Ping-Alive
    type: url-test
    disable-udp: false
    use:
      - ID
      - SG
    url: http://www.gstatic.com/generate_204
    interval: '120'
    tolerance: '10'
  - name: LoadBalancing
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use:
      - ID
      - SG
    url: http://www.gstatic.com/generate_204
    interval: '120'
    tolerance: '10'
rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,Direct,DIRECT
  - RULE-SET,UDP,UDP-Traffic
  - GEOSITE,bank-id,Indo-Traffic
  - GEOSITE,rule-indo,Indo-Traffic
  - GEOSITE,rule-sosmed,Indo-Traffic
  - GEOSITE,rule-streaming,Indo-Traffic
  - GEOSITE,rule-gaming,UDP-Traffic
  - GEOSITE,rule-speedtest,PILIH
  - GEOSITE,urltest,Ping-Alive
  - MATCH,GLOBAL
dns:
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  proxy-server-nameserver:
    - 112.215.198.248
    - 112.215.198.254
    - 112.215.203.246
    - 112.215.203.247
    - 112.215.203.248
    - 112.215.203.254
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - 1.0.0.1
    - tls://dns.google
    - https://dns.google/dns-query
  enable: true
  listen: '[::]:1053'
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  respect-rules: true
  prefer-h3: false
  use-system-hosts: true
  use-hosts: true
log-level: silent
mode: rule
find-process-mode: off
ipv6: false
unified-delay: true
tcp-concurrent: true
disable-keep-alive: false
keep-alive-idle: 10
keep-alive-interval: 1
external-ui: ui
external-ui-name: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip
external-controller: '[::]:9090'
allow-lan: true
port: 8080
socks-port: 1080
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
authentication:
  - nikki:antfrgl
tun:
  enable: true
  device: nikki
  stack: system
  mtu: 1500
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
sniffer:
  enable: false
  force-dns-mapping: false
  parse-pure-ip: false
profile:
  store-selected: true
  store-fake-ip: false
geox-url:
  geosite: https://github.com/antifragile0/GeoSite-WRT/releases/download/latest/geosite.dat
  geoip: https://github.com/antifragile0/GeoSite-WRT/releases/download/latest/geoip.dat
geo-auto-update: true
geo-update-interval: 168
proxies: null
